### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ckiee** [choroba/small-scripts#4]
I got here by searching [DDG](https://duckduckgo.com/?q=git+commits+per+day+gnuplot&t=ffab&ia=web&iax=qa) and git-graph does the thing I wanted. Is this okay to use by you? No license so better to ask. 

(Also, if I were to theoretically ignore IP law I'm sure I would thank you for writing this!)

**Comment by choroba** [comment]
I added GPL2 to the README. Thank you!

**Comment by ckiee** [comment]
Cheers!
